const siteConfig = {
  name: "Herceg Novi Car Hire",
  tagline: "Drive the Boka Bay Entrance",
  domain: "hercegnovicarhire.com",
  phone: "",
  email: "info@hercegnovicarhire.com",
  address: "Herceg Novi, Montenegro",

  hero: {
    headline: "Explore Herceg Novi at Your Own Pace",
    subheadline: "Pick up your rental car in Herceg Novi — just 35km from Tivat Airport and the gateway from Dubrovnik into Montenegro.",
    image: "/img/hero-herceg-novi.webp",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      name: "VW Polo",
      category: "Economy",
      price: 25,
      image: "/img/pexels-1035108.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      popular: false,
    },
    {
      id: 2,
      slug: "skoda-octavia",
      name: "Skoda Octavia",
      category: "Mid-Size",
      price: 35,
      image: "/img/pexels-116675.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Automatic Transmission", "Cruise Control", "Parking Sensors", "Large Boot"],
      popular: true,
    },
    {
      id: 3,
      slug: "toyota-corolla",
      name: "Toyota Corolla",
      category: "Mid-Size",
      price: 38,
      image: "/img/pexels-170811.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Hybrid Engine", "Reversing Camera", "Apple CarPlay", "Keyless Start"],
      popular: false,
    },
    {
      id: 4,
      slug: "mercedes-c-class",
      name: "Mercedes C-Class",
      category: "Premium",
      price: 65,
      image: "/img/pexels-120049.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Leather Seats", "Navigation System", "Premium Sound", "Heated Seats"],
      popular: true,
    },
    {
      id: 5,
      slug: "jeep-renegade",
      name: "Jeep Renegade",
      category: "SUV",
      price: 55,
      image: "/img/pexels-1638459.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["4x4 Drive", "Hill Descent Control", "Roof Rails", "Off-Road Mode"],
      popular: false,
    },
    {
      id: 6,
      slug: "bmw-x3",
      name: "BMW X3",
      category: "Premium SUV",
      price: 85,
      image: "/img/pexels-892522.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Panoramic Roof", "Adaptive Cruise", "360 Camera", "Sport Mode"],
      popular: false,
    },
    {
      id: 7,
      slug: "fiat-500",
      name: "Fiat 500",
      category: "City",
      price: 20,
      image: "/img/pexels-1007410.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      popular: false,
    },
    {
      id: 8,
      slug: "vw-transporter",
      name: "VW Transporter",
      category: "Van",
      price: 70,
      image: "/img/pexels-2533092.jpg",
      seats: 9,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 6,
      ac: true,
      features: ["9 Seats", "Airport Shuttle Ready", "Sliding Doors", "Ample Storage"],
      popular: false,
    },
  ],

  features: [
    { icon: "map-pin", title: "Airport Pickup", description: "Tivat Airport is 35 km away — take the scenic bay road or the Verige ferry shortcut. Your choice, your schedule." },
    { icon: "shield-check", title: "Full Insurance", description: "Full CDW coverage with zero excess option. Essential for the narrow lanes of the old town and the Croatian motorway beyond Debeli Brijeg." },
    { icon: "clock", title: "24/7 Support", description: "Igalo checkup ran late? We'll rearrange your pickup time. Roadside assistance available whenever you need us." },
    { icon: "ban", title: "No Hidden Fees", description: "One transparent price — mileage, VAT, and cross-border surcharges for Croatia are all included. No surprises at pickup." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Spa treatment overran or your Dubrovnik day trip plans shifted? Cancel or reschedule up to 24 hours before pickup, free of charge." },
    { icon: "globe", title: "Cross-Border to Croatia", description: "Dubrovnik is just 30 km from Herceg Novi via the Debeli Brijeg crossing — the closest Montenegrin town to Croatia. Green card included." },
  ],

  testimonials: [
    { name: "Mia & Erik Laine", location: "Helsinki, Finland", text: "We came for the Igalo mud treatments and left with memories of the whole bay. Having a car meant we could visit Kotor between spa sessions and catch the Savina Monastery gardens in the morning light. Perfectly organised rental.", rating: 5, avatar: "/img/avatar-1.webp" },
    { name: "Isabelle Dumont", location: "Lyon, France", text: "The botanical gardens of Herceg Novi were magical in spring, and the car made it so easy to drive to Dubrovnik for the day. The Debeli Brijeg crossing took barely twenty minutes. All the documents were ready at pickup.", rating: 5, avatar: "/img/avatar-2.webp" },
    { name: "Tomáš Kovář", location: "Prague, Czech Republic", text: "Forte Mare at sunset, the view from Savina across the bay, and then the long golden drive back along the water — I photographed it all. The car was clean, the handover was smooth, and they even suggested the best light for the fortress.", rating: 5, avatar: "/img/avatar-3.webp" },
  ],

  faq: [
    { q: "What documents do I need?", a: "Bring a valid driving licence showing Latin-script details, your passport, and a physical credit card in the main driver's name. If your licence was issued outside the EU or EEA, an International Driving Permit is recommended. Electronic copies and photocopies are not accepted by rental agents." },
    { q: "Can I drive to Croatia or Albania?", a: "Yes — and from Herceg Novi it is remarkably easy. Dubrovnik is only 30 km away via the Debeli Brijeg border crossing. Let us know at booking and we will ensure the Green Card and cross-border documentation are ready before you collect the car." },
    { q: "Is there a minimum age?", a: "The minimum age to rent is 21, and drivers must hold a full licence for at least two years. Drivers aged 21–24 pay a young driver supplement, and the exact amount varies by vehicle class — it is shown clearly in the search results before you confirm." },
    { q: "What's included in the price?", a: "All vehicles include Third Party Liability insurance and most include CDW in the base price. VAT, a mandatory equipment kit (first-aid box, warning triangle, reflective vest), and a transparent fuel policy are also included. Mileage terms vary by vehicle — check the listing details. Extended zero-excess cover is available as an add-on." },
    { q: "How does pickup work?", a: "We offer delivery to Herceg Novi town centre, the Igalo spa quarter, or a meet-and-greet at Tivat Airport arrivals — 35 km along the bay road, roughly 40 minutes. Choose your preferred location during booking and the agent will confirm the exact meeting point." },
    { q: "Can I drop off at a different location?", a: "Yes — one-way rentals are available across 28 locations throughout Montenegro. You can return the car in Podgorica, Kotor, Budva, or even Tivat Airport. Select separate pickup and drop-off points when booking." },
    { q: "Can I cancel my booking?", a: "Standard vehicles offer free cancellation up to 7 days before the rental start. Luxury cars and convertibles require 30 days' notice for a free cancellation. A 6% payment processing fee applies to all cancellations regardless of timing. If you need to reschedule around a spa appointment or day trip, contact us and we will do our best to accommodate." },
    { q: "Is a deposit required?", a: "A security deposit is held on a physical credit card — the amount ranges from €50 to €300 depending on the vehicle category. Some economy cars are available without a deposit. The hold is released within a few working days after you return the car in its original condition." },
    { q: "What happens if I exceed the mileage limit?", a: "Vehicles with a mileage cap charge a per-kilometre fee for any distance driven above the agreed limit. The rate is shown in the vehicle details before you book. Many vehicles on our platform offer unlimited mileage, which is useful if you plan multiple Dubrovnik crossings or a longer bay road loop." },
    { q: "Are there hidden costs?", a: "None. The price displayed at search includes all taxes, mandatory fees, and any cross-border charges for Croatia that apply to your booking. What you see is exactly what you pay — no airport surcharges added at the last moment." },
    { q: "How much is the down payment?", a: "Confirming your booking requires a down payment of 15–20% of the total rental cost. The remaining balance is settled directly with the rental agent when you collect the vehicle, whether that is at Herceg Novi centre, Igalo, or Tivat Airport." },
    { q: "Can I rent without a credit card?", a: "A small number of vehicles are available for renters who do not have a credit card. These are clearly marked in the search results. For most cars, a physical credit card in the driver's name is required for the security deposit hold." },
  ],

  locations: [
    { name: "Herceg Novi Centre", tag: "Most Popular" },
    { name: "Igalo", tag: "Spa Town" },
    { name: "Tivat Airport", tag: "" },
    { name: "Savina Monastery", tag: "" },
    { name: "Kotor", tag: "" },
    { name: "Dubrovnik Airport", tag: "" },
  ],

  destinations: [
    {
      name: "Igalo",
      slug: "igalo",
      tag: "Spa & Health",
      desc: "Famous health resort, 5 minutes from Herceg Novi.",
      image: "/img/igalo-spa.webp",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "UNESCO Site",
      desc: "Medieval walled city, 45 minutes along the bay.",
      image: "/img/kotor-from-herceg.webp",
    },
    {
      name: "Tivat Airport",
      slug: "tivat-airport",
      tag: "35 min Drive",
      desc: "Closest airport to Herceg Novi via the bay road.",
      image: "/img/coastal-drive.webp",
    },
    {
      name: "Dubrovnik Airport",
      slug: "dubrovnik-airport",
      tag: "Cross-Border",
      desc: "Just 30km away across the Croatian border.",
      image: "/img/dubrovnik-nearby.webp",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "Beach Town",
      desc: "Riviera beaches and nightlife, 1 hour south.",
      image: "/img/herceg-novi-riviera.webp",
    },
    {
      name: "Perast",
      slug: "perast",
      tag: "Hidden Gem",
      desc: "Baroque village on the bay, 30 minutes away.",
      image: "/img/perast-nearby.webp",
    },
    {
      name: "Risan",
      slug: "kotor",
      tag: "Roman Mosaics",
      desc: "Ancient town with Roman mosaics, 20 min drive.",
      image: "/img/savina-monastery.webp",
    },
    {
      name: "Lustica Peninsula",
      slug: "tivat",
      tag: "Beaches",
      desc: "Secluded beaches and olive groves across the bay.",
      image: "/img/forte-mare.webp",
    },
  ],
};

export default siteConfig;
