const siteConfig = {
  name: "Herceg Novi Car Hire",
  tagline: "Drive the Boka Bay Entrance",
  domain: "hercegnovicarhire.com",
  phone: "",
  email: "info@hercegnovicarhire.com",
  address: "Herceg Novi, Montenegro",

  hero: {
    headline: "Explore Herceg Novi at Your Own Pace",
    subheadline: "Pick up your rental car in Herceg Novi — just 35km from Tivat Airport and the gateway from Dubrovnik into Montenegro.",
    image: "/img/pexels-3802510.jpg",
  },

  cars: [
    {
      id: 1,
      slug: "vw-polo",
      name: "VW Polo",
      category: "Economy",
      price: 25,
      image: "/img/pexels-1035108.jpg",
      seats: 5,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 4,
      luggage: 2,
      ac: true,
      features: ["Air Conditioning", "Bluetooth Audio", "USB Charging", "Central Locking"],
      popular: false,
    },
    {
      id: 2,
      slug: "skoda-octavia",
      name: "Skoda Octavia",
      category: "Mid-Size",
      price: 35,
      image: "/img/pexels-116675.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Automatic Transmission", "Cruise Control", "Parking Sensors", "Large Boot"],
      popular: true,
    },
    {
      id: 3,
      slug: "toyota-corolla",
      name: "Toyota Corolla",
      category: "Mid-Size",
      price: 38,
      image: "/img/pexels-170811.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Hybrid",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Hybrid Engine", "Reversing Camera", "Apple CarPlay", "Keyless Start"],
      popular: false,
    },
    {
      id: 4,
      slug: "mercedes-c-class",
      name: "Mercedes C-Class",
      category: "Premium",
      price: 65,
      image: "/img/pexels-120049.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["Leather Seats", "Navigation System", "Premium Sound", "Heated Seats"],
      popular: true,
    },
    {
      id: 5,
      slug: "jeep-renegade",
      name: "Jeep Renegade",
      category: "SUV",
      price: 55,
      image: "/img/pexels-1638459.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 3,
      ac: true,
      features: ["4x4 Drive", "Hill Descent Control", "Roof Rails", "Off-Road Mode"],
      popular: false,
    },
    {
      id: 6,
      slug: "bmw-x3",
      name: "BMW X3",
      category: "Premium SUV",
      price: 85,
      image: "/img/pexels-892522.jpg",
      seats: 5,
      transmission: "Automatic",
      fuel: "Diesel",
      doors: 4,
      luggage: 4,
      ac: true,
      features: ["Panoramic Roof", "Adaptive Cruise", "360 Camera", "Sport Mode"],
      popular: false,
    },
    {
      id: 7,
      slug: "fiat-500",
      name: "Fiat 500",
      category: "City",
      price: 20,
      image: "/img/pexels-1007410.jpg",
      seats: 4,
      transmission: "Manual",
      fuel: "Petrol",
      doors: 2,
      luggage: 1,
      ac: true,
      features: ["Compact Size", "Easy Parking", "Sunroof", "Bluetooth"],
      popular: false,
    },
    {
      id: 8,
      slug: "vw-transporter",
      name: "VW Transporter",
      category: "Van",
      price: 70,
      image: "/img/pexels-2533092.jpg",
      seats: 9,
      transmission: "Manual",
      fuel: "Diesel",
      doors: 4,
      luggage: 6,
      ac: true,
      features: ["9 Seats", "Airport Shuttle Ready", "Sliding Doors", "Ample Storage"],
      popular: false,
    },
  ],

  features: [
    { icon: "map-pin", title: "Airport Pickup", description: "Collect your car at Tivat Airport or arrange delivery to Herceg Novi. No shuttle, no waiting." },
    { icon: "shield-check", title: "Full Insurance", description: "Comprehensive coverage with zero excess option. Drive with complete peace of mind." },
    { icon: "clock", title: "24/7 Support", description: "Roadside assistance and customer service available around the clock, every day." },
    { icon: "ban", title: "No Hidden Fees", description: "Fuel policy, mileage, tax — everything is included in the price you see." },
    { icon: "refresh-cw", title: "Free Cancellation", description: "Plans change. Cancel up to 24 hours before pickup for a full refund." },
    { icon: "globe", title: "Cross-Border to Croatia", description: "Drive across the Croatian border to Dubrovnik and beyond. Cross-border travel permitted." },
  ],

  testimonials: [
    { name: "James Wilson", location: "London, UK", text: "Picked up our car in Herceg Novi and drove the Dubrovnik corridor the same afternoon. Paperwork for Croatia was ready. Brilliant service.", rating: 5, avatar: "/img/pexels-220453.jpg" },
    { name: "Katrin Meier", location: "Munich, Germany", text: "We stayed in Igalo for the spa and used the rental to explore Kotor, Perast, and Budva. The golden coastline is stunning from a car.", rating: 5, avatar: "/img/pexels-774909.jpg" },
    { name: "Tom & Sarah", location: "Melbourne, Australia", text: "Herceg Novi was our base for two weeks. The Jeep handled the bay road to Tivat perfectly and we crossed into Croatia three times.", rating: 5, avatar: "/img/pexels-1222271.jpg" },
  ],

  faq: [
    { q: "What documents do I need?", a: "A valid driving licence, passport or ID, and a credit card in the main driver's name. International Driving Permit required for non-EU licences." },
    { q: "Can I drive to Croatia or Albania?", a: "Yes! Cross-border travel is permitted to Croatia, Bosnia, Albania, Kosovo, and Serbia. Just let us know at booking and we'll prepare the Green Card." },
    { q: "Is there a minimum age?", a: "The minimum age is 21 with at least 2 years driving experience. Drivers under 25 pay a small young driver supplement of \u20AC5/day." },
    { q: "What's included in the price?", a: "Full insurance (CDW + theft protection), unlimited mileage, VAT, airport pickup/dropoff, 24/7 roadside assistance, and a free second driver." },
    { q: "How does pickup work?", a: "We can deliver your car to Herceg Novi centre, Igalo, or meet you at Tivat Airport arrivals. Total time from landing to driving: about 10 minutes." },
    { q: "Can I drop off at a different location?", a: "Yes \u2014 one-way rentals are supported across 28 cities and towns in Montenegro. Simply choose different pickup and dropoff locations during booking." },
    { q: "Can I cancel my booking?", a: "Free cancellation up to 7 days before the rental start date. For luxury cars and convertibles, free cancellation is available up to 30 days before. A 6% payment service fee applies to all cancellations." },
    { q: "Is a deposit required?", a: "Deposits range from \u20AC50 to \u20AC300 depending on the vehicle. Some cars are available with no deposit. The deposit must be on a physical credit card in the driver's name and is refunded upon return of the vehicle in good condition." },
    { q: "What happens if I exceed the mileage limit?", a: "For vehicles with a mileage limit, an additional charge per extra kilometre applies above the agreed limit. The rate is specified in the rental terms for the vehicle." },
    { q: "Are there hidden costs?", a: "The final rental price includes all taxes and fees \u2014 there are no hidden costs." },
    { q: "How much is the down payment?", a: "A down payment of 15\u201320% is required to confirm your booking. The remaining balance is paid to the rental company at pickup." },
    { q: "Can I rent without a credit card?", a: "Some vehicles can be rented without a credit card \u2014 available options are marked in the search results." },
  ],

  locations: [
    { name: "Herceg Novi Centre", tag: "Most Popular" },
    { name: "Igalo", tag: "Spa Town" },
    { name: "Tivat Airport", tag: "" },
    { name: "Savina Monastery", tag: "" },
    { name: "Kotor", tag: "" },
    { name: "Dubrovnik Airport", tag: "" },
  ],

  destinations: [
    {
      name: "Igalo",
      slug: "kotor",
      tag: "Spa & Health",
      desc: "Famous health resort, 5 minutes from Herceg Novi.",
      image: "/img/pexels-5668157.jpg",
    },
    {
      name: "Kotor",
      slug: "kotor",
      tag: "UNESCO Site",
      desc: "Medieval walled city, 45 minutes along the bay.",
      image: "/img/pexels-5668157.jpg",
    },
    {
      name: "Tivat Airport",
      slug: "tivat-airport",
      tag: "35 min Drive",
      desc: "Closest airport to Herceg Novi via the bay road.",
      image: "/img/pexels-16099591.jpg",
    },
    {
      name: "Dubrovnik Airport",
      slug: "dubrovnik-airport",
      tag: "Cross-Border",
      desc: "Just 30km away across the Croatian border.",
      image: "/img/pexels-30006498.jpg",
    },
    {
      name: "Budva",
      slug: "budva",
      tag: "Beach Town",
      desc: "Riviera beaches and nightlife, 1 hour south.",
      image: "/img/pexels-26753897.jpg",
    },
    {
      name: "Perast",
      slug: "perast",
      tag: "Hidden Gem",
      desc: "Baroque village on the bay, 30 minutes away.",
      image: "/img/pexels-29904099.jpg",
    },
    {
      name: "Risan",
      slug: "kotor",
      tag: "Roman Mosaics",
      desc: "Ancient town with Roman mosaics, 20 min drive.",
      image: "/img/pexels-9526645.jpg",
    },
    {
      name: "Lustica Peninsula",
      slug: "tivat",
      tag: "Beaches",
      desc: "Secluded beaches and olive groves across the bay.",
      image: "/img/pexels-6216512.jpg",
    },
  ],
};

export default siteConfig;
